### ISSUE TITLE
Return custom error on invalid token auth

### ISSUE THREAD

**Issue by enzoftware** [boxting/boxting-backend#16]
<img src="https://user-images.githubusercontent.com/22333076/115163452-d0829e80-a06e-11eb-8ce0-bac447462e55.png" width="960" />

**Comment by RodrigoAGM** [comment]
Solved on [commit 8b1328a](https://github.com/boxting/boxting-backend/commit/8b1328a6d1146fb3684fd278807353e70b8f828d)
